/********************************************************************
* src/dictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/dictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictionary();
extern void G__cpp_setup_inheritancedictionary();
extern void G__cpp_setup_typetabledictionary();
extern void G__cpp_setup_memvardictionary();
extern void G__cpp_setup_globaldictionary();
extern void G__cpp_setup_memfuncdictionary();
extern void G__cpp_setup_funcdictionary();
extern void G__set_cpp_environmentdictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/tnm.h"
